#!/usr/bin/env sh
# Simple emacs based utility to indent a single file.

\emacs --batch "$@" \
       --eval "(progn (untabify (point-min) (point-max)) (delete-trailing-whitespace (point-min) (point-max)) (indent-region (point-min) (point-max)) (save-buffer))"
